### ISSUE TITLE
TS types for `RestElement` incorrect

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#2658] opened 2024-03-10 01:52 UTC
@ArnaudBarre said on https://github.com/oxc-project/oxc/pull/2652#issuecomment-1987009066 (relevant to #2463):

Just checked now the implication of your last PR (#2567). I'm still updating the wrapper, but the types are now a bit wrong because they are generated from the original struct and not the one used in the serializer. Do you think this is fixable?

**Comment by overlookmotel** [comment] 2024-03-10 01:53
> Just checked now the implication of your last PR (#2567). I'm still updating the wrapper, but the types are now a bit wrong because they are generated from the original struct and not the one used in the serializer. Do you think this is fixable?

Argh! I found `tsify` difficult. The types being generated from the original *should* be fine as it has `tsify(type = "...")` and `serde` attributes on the field which `tsify` macro uses to create the type defs:

https://github.com/oxc-project/oxc/blob/32303b20fb54aafa60138c7133e31429d2421df5/crates/oxc_ast/src/ast/js.rs#L1720-L1730

But I guess not...

It's tricky as CI checks that the type defs are valid (i.e. internally consistent), but doesn't notice if they don't match the actual AST objects.

Are you able to list which types are wrong? I'm sure I can fix them, but it'd help to have pointers where it's wrong (and were you checking them with a tool, or verifying them by eye?). Sorry to ask - but if you have time to give more info, I'll be able to get them fixed faster.

**Comment by ArnaudBarre** [comment] 2024-03-10 02:00
I'm not using special tools to detect differences, but I notice when things go wrong when I'm unable to update my wrapper implementation because of missing fields

**Comment by ArnaudBarre** [comment] 2024-03-10 17:21
yes #2670 should fix the other type issues mentioned in previous comments.
Sorry for the confusion, because both type regression where linked to a merged PR and your PR was about to fix some issues about that I though this was simpler to report there, but I will open separate issues next time :)

**Comment by overlookmotel** [comment] 2024-03-10 17:50
OK great. Thanks for clarifying. Glad the various glitches you found are all now (hopefully) ironed out.

**Closed** 2024-03-11 05:42 UTC
