### ISSUE TITLE
VSCode extension is using the latest version, not the one in my `package.json`

### ISSUE THREAD

**Issue by tylerlaprade** [oxc-project/oxc#5330] opened 2024-08-29 19:55 UTC
Recently I started getting a bunch of errors for `prefer-spread` all over my codebase, but I don't get them in the CLI because my `package.json` has `"oxlint": "0.6.1"` pinned

**Comment by rzvxa** [comment] 2024-09-04 22:30
duplicate of #3426

**Closed by rzvxa** 2024-09-04 22:30 UTC
Labels: C-bug
