### ISSUE TITLE
Rust 1.80.0 regresses `prepass` benchmarks by 13%

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#4478] opened 2024-07-26 10:12 UTC
#4474 upgraded to Rust 1.80.0. Bizarrely, this change seems to have resulted in up to -13% perf regression on `prepass` benchmarks.

Benchmarks didn't run on the PR for upgrade #4474, but the effect is visible on #4479.

**Comment by rzvxa** [comment] 2024-07-27 05:06
After upgrading to Rust 1.80.0 we are experiencing up to 13% benchmark regression, There are no red flags in the changelog so I'm not sure what the culprit is.

**Comment by Boshen** [comment] 2024-08-05 09:38
Seems like caused by `main` branch not having the latest benchmark results. Fixed by always run benchmark on `main` (regarding changing rust version).

**Closed by Boshen** 2024-08-05 09:38 UTC
Labels: C-bug

**Comment by overlookmotel** [comment] 2024-08-05 18:09
@Boshen I'm afraid I don't think that's the explanation.

<img width="1076" alt="bench-prepass" src="https://github.com/user-attachments/assets/d7f5ceba-7ce9-4e75-a70f-31e3a3b23931">

Red circle is upgrade to Rust 1.80.0. It wasn't a temporary glitch in benchmarks - it's endured ever since.

But I have no idea what could have caused it, or what we can do about it! Do you think it's worth looking into?

**Comment by Boshen** [comment] 2024-08-06 00:38
> Do you think it's worth looking into?

No, let's spend our time else where.
