### ISSUE TITLE
[oxlint]   js文件与vue sfc中对jsx的处理保持一致

### ISSUE THREAD

**Issue by 2096903746** [oxc-project/oxc#4582] opened 2024-07-31 08:23 UTC
在执行lint检查的时候：

包含 "js" | "mjs" | "cjs" | "jsx" | "tsx"扩展的SourceType.variant 默认都会被定义成 jsx，并当成jsx去处理。

但是vue sfc文件内script不会被默认成jsx (需要手动指定lang=jsx)，能否与上面保持一致。

老项目中，有大量未指定lang=jsx的vue sfc文件，改动量太大。

**Comment by Boshen** [comment] 2024-07-31 09:16
@mysteryven I think our default is correct and conform to the standard?

> 有大量未指定lang=jsx的vue sfc文件

Is a code mod too hard to write here or are there other complexities?

**Comment by mysteryven** [comment] 2024-07-31 11:01
It's expected behavior when I tested it, it didn't auto-recognize JSX without `lang` : https://stackblitz.com/edit/vitejs-vite-3pibzp?file=src%2FApp.vue

Could you provide a minimal reproduction?

**Comment by Boshen** [comment] 2024-07-31 11:04
I saw somewhere it works with jsx plugin in `.babelrc` 😅

**Comment by mysteryven** [comment] 2024-07-31 14:20
> 所以能否在这里默认就开启jsx，而不用指定 lang="jsx":

The incorrect variant of file may cause other potential problems. We're going to close this because for the same reason as #2304.

If you accept change your codebases,  you can add me on Discord, I can help you write a litter script to fix this.

Discord: mysteryven

**Closed by mysteryven** 2024-07-31 14:20 UTC
Labels: C-enhancement
