### ISSUE TITLE
isolatedDeclaration strips docstrings

### ISSUE THREAD

**Issue by MichaelMitchell-at** [oxc-project/oxc#3915] opened 2024-06-26 03:04 UTC
```
> require('oxc-transform').isolatedDeclaration("hello.ts", `
... /**
...  * Docstring
...  */
... export function foo(): number { return 42 }
... `)
{ sourceText: 'export declare function foo(): number;\n', errors: [] }
```

**Comment by Boshen** [comment] 2024-06-30 10:23
Duplicate of https://github.com/oxc-project/oxc/issues/3906

**Closed by Boshen** 2024-06-30 10:23 UTC
Labels: C-bug
