### ISSUE TITLE
Import plugin hangs if .json imports exist

### ISSUE THREAD

**Issue by danielfrenda** [oxc-project/oxc#2036] opened 2024-01-15 11:12 UTC
I've found that the the following command is hanging if there is a `.json` import, usually 3+ indirections away from the target.
`oxlint --import-plugin`

I've tried and failed to create a minimal reproduction, We've got a fairly complex codebase with a lot of legacy code and a mix of import/export flavours. But hunting these down and commenting out the JSON imports allows oxlint to run.

I've also tried import type assertions/attributes to see if that fixed my issues, however they did not.

**Comment by Boshen** [comment] 2024-01-15 12:38
Thank you for trying out `--import-plugin`, it is still an experimental feature with a lot of edge cases :-(

**Comment by danielfrenda** [comment] 2024-01-15 20:09
Yeah I realise that, but I _am_ already finding it very useful, the hang itself has helped me track down some potential bugs (in a binary search kind of way)

**Comment by Boshen** [comment] 2024-01-22 08:43
I couldn't replicate this, the bug is probably not just because it's not handled.

https://github.com/oxc-project/oxc/blob/69fecac7333ce1b61af0aff9a96018a138422eea/crates/oxc_linter/src/service.rs#L166-L168

It's probably some race condition that's hard to reproduce.

I'll close this for now.

**Closed by Boshen** 2024-01-22 08:43 UTC
