### ISSUE TITLE
transform: preserve comments in DTS output

### ISSUE THREAD

**Issue by lukeed** [oxc-project/oxc#5396] opened 2024-09-02 06:54 UTC
There should be an option to preserve JSDoc comments for DTS generation. This is typically where authors write method documentation/examples. The JSR (and Deno, by extension) ecosystem score your package by (lack of) documentation, so for those who are dual-publishing to both npm & JSR, it'd be nice to have a DTS fully generated from the JSR-primary.

**Comment by Boshen** [comment] 2024-09-02 07:18
Oxc is missing infrastructure for comments, and I'm working on it as we speak.

Close as duplicate of https://github.com/oxc-project/oxc/issues/3906

**Closed by Boshen** 2024-09-02 07:18 UTC
Labels: C-enhancement

**Comment by lukeed** [comment] 2024-09-02 07:46
sorry, I searched for "comments" and didnt find prior art 😇

**Comment by Boshen** [comment] 2024-09-23 11:09
Released in https://www.npmjs.com/package/oxc-transform/v/0.30.0, along with the `stripInternal` option.
