### ISSUE TITLE
isolatedDeclarations: should preserve jsdoc comments

### ISSUE THREAD

**Issue by yyx990803** [oxc-project/oxc#5687] opened 2024-09-11 00:43 UTC
Currently, all comments are stripped during isolatedDeclaration transform. JSDoc comments are necessary for in-IDE documentation on hover, so JSDoc comments attached to types should be preserved in dts files.

**Comment by Boshen** [comment] 2024-09-13 03:14
Duplicate of #1046 and #3906

**Closed by Boshen** 2024-09-13 03:14 UTC
Labels: C-bug

**Comment by Boshen** [comment] 2024-09-23 11:09
Released in https://www.npmjs.com/package/oxc-transform/v/0.30.0, along with the `stripInternal` option.
